### ISSUE TITLE
OAuth issue

### ISSUE THREAD

**Issue by jamiefolsom** [performant-software/Annotation-Studio#121]
When a user creates a new account at http://navsa.org, then visits http://studio.covecollective.org, and clicks log in > log in through NAVSA, upon redirect, they get a server error. 

Here's a stacktrace:

```
A NoMethodError occurred in omniauth_callbacks#wordpress_hosted:

undefined method `persisted?' for nil:NilClass
app/controllers/omniauth_callbacks_controller.rb:5:in `wordpress_hosted'
------------------------------- Request:

* URL        : http://studio.covecollective.org/users/auth/wordpress_hosted/callback?code=gmz0kdcdfksimcnyzlepwjvcrbfjuxuiruqbepj3&state=d71a080fbd6326699f52efed33ddce31d0d96ead748cc89e
* HTTP Method: GET
* IP address : 129.62.67.110
* Parameters : {"code"=>"[FILTERED]", "state"=>"d71a080fbd6326699f52efed33ddce31d0d96ead748cc89e", "controller"=>"omniauth_callbacks", "action"=>"wordpress_hosted"}
* Timestamp  : 2017-09-20 16:32:27 UTC
* Server : c1cece15-7421-4427-a5f1-2707a68d51e8
* Rails root : /app
* Process: 18
------------------------------- Session:

* session id: "acde60ef189af4a721e00d57ce8a42f1"
* data: {"session_id"=>"acde60ef189af4a721e00d57ce8a42f1",
 "user_return_to"=>"/documents/in-an-artists-studio",
 "_csrf_token"=>"v1D3Ev9ue1jCS6sOkD67rbGFLcOTXsTY50Qh8KXKOx8="}
------------------------------- Environment:

 * GATEWAY_INTERFACE                              : CGI/1.2
 * HTTP_ACCEPT                                    : text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
 * HTTP_ACCEPT_ENCODING                           : gzip, deflate
 * HTTP_ACCEPT_LANGUAGE                           : en-US,en;q=0.8
 * HTTP_CACHE_CONTROL                             : max-age=0
 * HTTP_CONNECTION                                : close
 * HTTP_CONNECT_TIME                              : 0
 * HTTP_COOKIE                                    : __utma=102918722.476024985.1505351632.1505869712.1505924943.7; __utmb=102918722.0.10.1505924943; __utmc=102918722; __utmz=102918722.1505351632.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _AnnotationStudio_session=TGxPQ084SEdMOHdVUEVJaTVtNkd1aG1OVmRKU004d09WOXVnK0dKZXYyM0k2Vmp5RHJxVDI0RUdBSTVaVHVIaEdGRklZMWgrNFpRYXlIWHh1cjk0NjNpMnZTZFBES25ScHNCdHdiVU1aejNnSUUzN3RWOFlqblFTZk9IZ2VDVVBZSGlGZmROZHQzR2xNSUJsMFlpM2FGQVJvNFM4NlJDblFORWN1QVRrcHJMWGJLTjE3NW40KzRMT1RRTE5LeGt3MS9uWmlCbnFaR2NXemYyT3d0bUtYdFhhcDh5QjZBTk1WcDB2NVFNd21zQ1B6Q1dFQ0pKRXVmSFFNbjZ3bjJneCtORnBBMERPMU9nTTV6bmRSTnJkQkNMN1dLY1dub1BWVWlERFpXcmJOWEF2WDhJUnV1OUgva1JxM1h2YXIyNTBWaWx6c1RHVTRBZ3J5cFpHektsY0NiV3RTTHBVTUJWZDRJV1gyeTY4WXFzNnlwS1ZoM3ZJY0Q3bitLWlR1Y3hFVWFDdnFWcmxSYTVyQlkwY2lJN3NlSVoxRFFEak5BUFVoNDUzUmg3Uk5lWW9Ndm9BZzI4VEtDQUQ5ejBZdVQxdWJ5cGdSY1VHZWtPV0o4enl0dlhEZEE9PS0tUEZHTWJXVy9DMG5wMTd5U1NraXl4Zz09--c405c06e86dc5193bea8bd4f4865d9d9e1abe354
 * HTTP_HOST                                      : studio.covecollective.org
 * HTTP_TOTAL_ROUTE_TIME                          : 0
 * HTTP_UPGRADE_INSECURE_REQUESTS                 : 1
 * HTTP_USER_AGENT                                : Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.91 Safari/537.36
 * HTTP_VERSION                                   : HTTP/1.1
 * HTTP_VIA                                       : 1.1 vegur
 * HTTP_X_FORWARDED_FOR                           : 129.62.67.110
 * HTTP_X_FORWARDED_PORT                          : 80
 * HTTP_X_FORWARDED_PROTO                         : http
 * HTTP_X_REQUEST_ID                              : 49dea039-2bcf-4d3f-bd98-beff67fb9c6f
 * HTTP_X_REQUEST_START                           : 1505925146214
 * ORIGINAL_FULLPATH                              : /users/auth/wordpress_hosted/callback?code=gmz0kdcdfksimcnyzlepwjvcrbfjuxuiruqbepj3&state=d71a080fbd6326699f52efed33ddce31d0d96ead748cc89e
 * ORIGINAL_SCRIPT_NAME                           :
 * PATH_INFO                                      : /users/auth/wordpress_hosted/callback
 * QUERY_STRING                                   : code=gmz0kdcdfksimcnyzlepwjvcrbfjuxuiruqbepj3&state=d71a080fbd6326699f52efed33ddce31d0d96ead748cc89e
 * REMOTE_ADDR                                    : 10.150.73.107
 * REQUEST_METHOD                                 : GET
 * REQUEST_PATH                                   : /users/auth/wordpress_hosted/callback
 * REQUEST_URI                                    : /users/auth/wordpress_hosted/callback?code=gmz0kdcdfksimcnyzlepwjvcrbfjuxuiruqbepj3&state=d71a080fbd6326699f52efed33ddce31d0d96ead748cc89e
 * ROUTES_70270910911220_SCRIPT_NAME              :
 * SCRIPT_NAME                                    :
 * SERVER_NAME                                    : studio.covecollective.org
 * SERVER_PORT                                    : 80
 * SERVER_PROTOCOL                                : HTTP/1.1
 * SERVER_SOFTWARE                                : puma 3.6.0 Sleepy Sunday Serenity
 * action_controller.instance                     : #<OmniauthCallbacksController:0x007fd251889480>
 * action_dispatch.backtrace_cleaner              : #<Rails::BacktraceCleaner:0x007fd2720317a8>
 * action_dispatch.cookies                        : #<ActionDispatch::Cookies::CookieJar:0x007fd251c66620>
 * action_dispatch.cookies_digest                 :
 * action_dispatch.cookies_serializer             : marshal
 * action_dispatch.encrypted_cookie_salt          : encrypted cookie
 * action_dispatch.encrypted_signed_cookie_salt   : signed encrypted cookie
 * action_dispatch.http_auth_salt                 : http authentication
 * action_dispatch.key_generator                  : #<ActiveSupport::CachingKeyGenerator:0x007fd272b197b0>
 * action_dispatch.logger                         : #<RailsStdoutLogging::StdoutLogger:0x007fd271516f58>
 * action_dispatch.parameter_filter               : [:password, :password, :client_secret, :code, :token]
 * action_dispatch.redirect_filter                : []
 * action_dispatch.remote_ip                      : 129.62.67.110
 * action_dispatch.request.content_type           :
 * action_dispatch.request.formats                : [#<Mime::Type:0x007fd26e38b420 @synonyms=["application/xhtml+xml"], @symbol=:html, @string="text/html">]
 * action_dispatch.request.parameters             : {"code"=>"[FILTERED]", "state"=>"d71a080fbd6326699f52efed33ddce31d0d96ead748cc89e", "controller"=>"omniauth_callbacks", "action"=>"wordpress_hosted"}
 * action_dispatch.request.path_parameters        : {:controller=>"omniauth_callbacks", :action=>"wordpress_hosted"}
 * action_dispatch.request.query_parameters       : {"code"=>"[FILTERED]", "state"=>"d71a080fbd6326699f52efed33ddce31d0d96ead748cc89e"}
 * action_dispatch.request.request_parameters     : {}
 * action_dispatch.request.unsigned_session_cookie: {"session_id"=>"acde60ef189af4a721e00d57ce8a42f1", "user_return_to"=>"/documents/in-an-artists-studio", "_csrf_token"=>"[FILTERED]", "omniauth.params"=>{}, "omniauth.origin"=>"http://studio.covecollective.org/", "omniauth.state"=>"d71a080fbd6326699f52efed33ddce31d0d96ead748cc89e"}
 * action_dispatch.request_id                     : 49dea039-2bcf-4d3f-bd98-beff67fb9c6f
 * action_dispatch.routes                         : #<ActionDispatch::Routing::RouteSet:0x007fd2715da5e8>
 * action_dispatch.secret_key_base                : 20fca22ca09e3dd9e868ffd7572d370141384ecc2eefd6fea2b22d70e9f4128e65af42a2b82d3de07415794eafc4e9f4366f808b217dfd9c249426598ddb0998
 * action_dispatch.secret_token                   : [FILTERED]
 * action_dispatch.show_detailed_exceptions       : false
 * action_dispatch.show_exceptions                : true
 * action_dispatch.signed_cookie_salt             : signed cookie
 * devise.mapping                                 : #<Devise::Mapping:0x007fd272dc6148>
 * devise.skip_timeout                            : true
 * newrelic.transaction_started                   : true
 * omniauth.auth                                  : {"provider"=>"wordpress_hosted", "uid"=>"1222", "info"=>{"name"=>"Joshua King", "email"=>"Joshua_King@baylor.edu", "nickname"=>"joshua_king", "urls"=>{"Website"=>nil}}, "credentials"=>{"token"=>"[FILTERED]", "refresh_token"=>"[FILTERED]", "expires_at"=>1505928746, "expires"=>true}, "extra"=>{"raw_info"=>{"ID"=>"1222", "user_login"=>"joshua_king", "user_nicename"=>"joshua_king", "user_email"=>"Joshua_King@baylor.edu", "user_registered"=>"0000-00-00 00:00:00", "user_status"=>"0", "display_name"=>"Joshua King", "email"=>"Joshua_King@baylor.edu", "nickname"=>"joshua_king", "given_name"=>"Joshua", "family_name"=>"King"}}}
 * omniauth.origin                                : http://studio.covecollective.org/
 * omniauth.params                                : {}
 * omniauth.strategy                              : #<OmniAuth::Strategies::WordpressHosted:0x007fd251c74770>
 * puma.config                                    : #<Puma::Configuration:0x007fd26d7c9ee8>
 * puma.socket                                    : #<TCPSocket:0x007fd251cf5488>
 * rack.after_reply                               : []
 * rack.errors                                    : #<IO:0x007fd26c7ad550>
 * rack.hijack                                    : #<Puma::Client:0x007fd251cf5460>
 * rack.hijack?                                   : true
 * rack.input                                     : #<Puma::NullIO:0x007fd26d78a8d8>
 * rack.multiprocess                              : false
 * rack.multithread                               : true
 * rack.request.cookie_hash                       : {"__utma"=>"102918722.476024985.1505351632.1505869712.1505924943.7", "__utmb"=>"102918722.0.10.1505924943", "__utmc"=>"102918722", "__utmz"=>"102918722.1505351632.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)", "_AnnotationStudio_session"=>"TGxPQ084SEdMOHdVUEVJaTVtNkd1aG1OVmRKU004d09WOXVnK0dKZXYyM0k2Vmp5RHJxVDI0RUdBSTVaVHVIaEdGRklZMWgrNFpRYXlIWHh1cjk0NjNpMnZTZFBES25ScHNCdHdiVU1aejNnSUUzN3RWOFlqblFTZk9IZ2VDVVBZSGlGZmROZHQzR2xNSUJsMFlpM2FGQVJvNFM4NlJDblFORWN1QVRrcHJMWGJLTjE3NW40KzRMT1RRTE5LeGt3MS9uWmlCbnFaR2NXemYyT3d0bUtYdFhhcDh5QjZBTk1WcDB2NVFNd21zQ1B6Q1dFQ0pKRXVmSFFNbjZ3bjJneCtORnBBMERPMU9nTTV6bmRSTnJkQkNMN1dLY1dub1BWVWlERFpXcmJOWEF2WDhJUnV1OUgva1JxM1h2YXIyNTBWaWx6c1RHVTRBZ3J5cFpHektsY0NiV3RTTHBVTUJWZDRJV1gyeTY4WXFzNnlwS1ZoM3ZJY0Q3bitLWlR1Y3hFVWFDdnFWcmxSYTVyQlkwY2lJN3NlSVoxRFFEak5BUFVoNDUzUmg3Uk5lWW9Ndm9BZzI4VEtDQUQ5ejBZdVQxdWJ5cGdSY1VHZWtPV0o4enl0dlhEZEE9PS0tUEZHTWJXVy9DMG5wMTd5U1NraXl4Zz09--c405c06e86dc5193bea8bd4f48
65d9d9e1abe354"}
 * rack.request.cookie_string                     : __utma=102918722.476024985.1505351632.1505869712.1505924943.7; __utmb=102918722.0.10.1505924943; __utmc=102918722; __utmz=102918722.1505351632.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); _AnnotationStudio_session=TGxPQ084SEdMOHdVUEVJaTVtNkd1aG1OVmRKU004d09WOXVnK0dKZXYyM0k2Vmp5RHJxVDI0RUdBSTVaVHVIaEdGRklZMWgrNFpRYXlIWHh1cjk0NjNpMnZTZFBES25ScHNCdHdiVU1aejNnSUUzN3RWOFlqblFTZk9IZ2VDVVBZSGlGZmROZHQzR2xNSUJsMFlpM2FGQVJvNFM4NlJDblFORWN1QVRrcHJMWGJLTjE3NW40KzRMT1RRTE5LeGt3MS9uWmlCbnFaR2NXemYyT3d0bUtYdFhhcDh5QjZBTk1WcDB2NVFNd21zQ1B6Q1dFQ0pKRXVmSFFNbjZ3bjJneCtORnBBMERPMU9nTTV6bmRSTnJkQkNMN1dLY1dub1BWVWlERFpXcmJOWEF2WDhJUnV1OUgva1JxM1h2YXIyNTBWaWx6c1RHVTRBZ3J5cFpHektsY0NiV3RTTHBVTUJWZDRJV1gyeTY4WXFzNnlwS1ZoM3ZJY0Q3bitLWlR1Y3hFVWFDdnFWcmxSYTVyQlkwY2lJN3NlSVoxRFFEak5BUFVoNDUzUmg3Uk5lWW9Ndm9BZzI4VEtDQUQ5ejBZdVQxdWJ5cGdSY1VHZWtPV0o4enl0dlhEZEE9PS0tUEZHTWJXVy9DMG5wMTd5U1NraXl4Zz09--c405c06e86dc5193bea8bd4f4865d9d9e1abe354
 * rack.request.query_hash                        : {"code"=>"[FILTERED]", "state"=>"d71a080fbd6326699f52efed33ddce31d0d96ead748cc89e"}
 * rack.request.query_string                      : code=gmz0kdcdfksimcnyzlepwjvcrbfjuxuiruqbepj3&state=d71a080fbd6326699f52efed33ddce31d0d96ead748cc89e
 * rack.run_once                                  : false
 * rack.session                                   : #<ActionDispatch::Request::Session:0x007fd251cc8848>
 * rack.session.options                           : #<ActionDispatch::Request::Session::Options:0x007fd251cc8780>
 * rack.url_scheme                                : http
 * rack.version                                   : [1, 3]
 * warden                                         : Warden::Proxy:70270646083100 @config={:default_scope=>:user, :scope_defaults=>{}, :default_strategies=>{:user=>[:database_authenticatable], :admin_user=>[:rememberable, :database_authenticatable]}, :intercept_401=>false, :failure_app=>#<Devise::Delegator:0x007fd2717be120>}
------------------------------- Backtrace:

app/controllers/omniauth_callbacks_controller.rb:5:in `wordpress_hosted'
config/initializers/quiet_assets.rb:6:in `call_with_quiet_assets'

```

**Comment by jamiefolsom** [comment]
@akstuhl if you have a moment to look at this, that would be great. If not just let me know. Thanks!

**Comment by jamiefolsom** [comment]
@akstuhl ok, thanks. I will chat you the user in question on slack.
